name: Deploy GCP Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Decode and save GCP service account key
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 --decode > gcp-key.json

      - name: Authenticate to Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project <YOUR_PROJECT_ID>

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan


